version: "3"

services:
  backend:
    build: .
    ports:
      - 3001:3001
    volumes:
      - ./backend:/app/backend
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
